flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint, render_template, request
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('home.jinja2', posts=posts)


@main.route('/about')
def about():
    return render_template('about.jinja2')

flaskblog/posts/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, abort
from flask_login import current_user, login_required
from flaskblog.posts.forms import PostForm
from flaskblog import db
from flaskblog.models import Post

posts = Blueprint('posts', __name__)


@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('New post has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('new_post.jinja2', title='New Post', form=form)


@posts.route('/posts/<int:post_id>')
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.jinja2', title=post.title, post=post)


@posts.route('/posts/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('update_post.jinja2', title='Update Post', form=form)


@posts.route('/posts/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import current_user, login_user, logout_user, login_required
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import send_reset_password_email, set_profile_picture
from flaskblog import bcrypt, db, mail
from flaskblog.models import User, Post

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash('You are already registered, if you want to create a new account, log out from the current one', 'info')
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(
            f'New account is created for {form.username.data}, You can log in now', 'success')
        return redirect(url_for('main.home'))

    return render_template('register.jinja2', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in, if you want to log in with another account, log out from the current one', 'info')
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('Successful login', 'success')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))
        else:
            flash('Unsuccessful log in, please check email and password', 'danger')

    return render_template('login.jinja2', title='Log in', form=form)


@users.route('/logout')
def logout():
    logout_user()
    flash('You are now logged out', 'info')
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.profile_picture.data:
            current_user.profile_picture = set_profile_picture(
                form.profile_picture.data)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account info updated successfully', 'success')
        return redirect(url_for('users.account'))
    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.jinja2', title='Account', form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.jinja2', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_password_email(user)
        flash(
            f'Please check the email address {form.email.data} for instructions to reset your password.\nIf you can\'t find the email, check the spams folder', 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.jinja2', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Invalid or expired token', 'danger')
        return redirect(url_for('users.request_reset'))
    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(
            f'New password has ben updated {user.username}, You can log in now', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.jinja2', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "base.html" %}
{% block content %}
  <h1>About page</h1>
{% endblock content %}

flaskblog/templates/about.jinja2
{% extends "base.jinja2" %}
{% block content %}
  <h1>About page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends 'base.html' %}
{% block content %}
  <div class="account border rounded p-3 mb-3">
    <div class="account-card d-flex align-items-center flex-column flex-sm-row mb-3">
      <img src="{{ url_for('static', filename = 'profile_pics/' + current_user.profile_picture)}}"
           class="img-fluid rounded-circle me-sm-4 mb-3 mb-sm-0"
           alt="profile pic">
      <div>
        <h5 class="card-title">{{ current_user.username }}</h5>
        <p class="card-text">
          <small class="text-muted">{{ current_user.email }}</small>
        </p>
      </div>
    </div>
    <form action="" method="post" enctype='multipart/form-data'>
      {{ form.hidden_tag()}}
      <fieldset class="from-group">
        <legend>
          Account Info
        </legend>
        <div class="mb-3">
          {{ form.username.label(class='form-label')}}
          {% if form.username.errors %}
            {{ form.username(class='form-control user-account-update-input')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.username.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.username(class='form-control user-account-update-input')}}
          {% endif %}
        </div>
        <div class="mb-3">
          {{ form.email.label(class='form-label')}}
          {% if form.email.errors %}
            {{ form.email(class='form-control user-account-update-input')}}
            <div class='invalid-feedback  d-block'>
              {% for error in form.email.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.email(class='form-control user-account-update-input')}}
          {% endif %}
        </div>
        <div class="mb-3">
          {{ form.profile_picture.label(class='form-label')}}
          {% if form.profile_picture.errors %}
            {{ form.profile_picture(class='form-control upload-profile-picture')}}
            <div class='invalid-feedback  d-block'>
              {% for error in form.profile_picture.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.profile_picture(class='form-control upload-profile-picture')}}
          {% endif %}
        </div>
      </fieldset>
      <div>{{ form.submit(class='btn btn-primary mb-3 update-account-submit')}}</div>
    </form>
  </div>
{% endblock content %}

flaskblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename = 'css/base.css') }}">
    {% if title %}
      <title>Flask blog - {{ title }}</title>
    {% else %}
      <title>Flask blog</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light text-white px-5 mb-3">
      <div class="container">
        <a class="navbar-brand text-white" href="#">Flask blog</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex align-center justify-content-between w-100">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('home') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('about') }}">About</a>
              </li>
            </ul>
            {% if current_user.is_authenticated %}
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('account') }}">Account</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('logout') }}">Log out</a>
                </li>
              </ul>
            {% else %}
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('register') }}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('login') }}">Log in</a>
                </li>
              </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
          {% for category, message in messages %}<div class='alert alert-{{ category }}'>{{ message }}</div>{% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock content %}
    </div>
    <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
  </body>
</html>

flaskblog/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.png')}}" />
    <link rel="stylesheet"
          href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename = 'css/base.css') }}">
    {% if title %}
      <title>Flask Blog - {{ title }}</title>
    {% else %}
      <title>Flask Blog</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light text-white px-5 mb-3">
      <div class="container">
        <a class="navbar-brand text-white" href="{{ url_for('main.home')}}">Flask blog</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#collapse"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapse">
          <div class="d-flex align-center justify-content-between w-100">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
              </li>
            </ul>
            {% if current_user.is_authenticated %}
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.logout') }}">Log out</a>
                </li>
              </ul>
            {% else %}
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.login') }}">Log in</a>
                </li>
              </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
          {% for category, message in messages %}<div class='alert alert-{{ category }}'>{{ message }}</div>{% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock content %}
    </div>
    <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
    <script src="{{ url_for('static', filename = 'js/update_post.js') }}"></script>
    <script src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>
  </body>
</html>

flaskblog/templates/home.html
{% extends "base.html" %}
{% block content %}
  {% for post in posts %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.author }} on {{ post.date }}</p>
    <p>{{ post.content }}</p>
  {% endfor %}
{% endblock content %}

flaskblog/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
  {% for post in posts.items %}
    <div class="post border rounded p-3 mb-3">
      <div class="post-card d-flex align-items-center flex-row  mb-3">
        <img src="{{ url_for('static', filename = 'profile_pics/' + post.author.profile_picture)}}"
             class="img-fluid rounded-circle me-4 "
             alt="profile pic">
        <div>
          <div class="card-text">
            <p class="mb-0">
              <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            </p>
            <small ><a class="text-muted"
   href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.date.strftime("%Y-%d-%m, %H:%M") }}</a></small>
          </div>
        </div>
      </div>
      <h5 class="card-title mb-2">
        <a class="link-dark" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
      </h5>
      <p>{{ post.content }}</p>
    </div>
  {% endfor %}
  <div class="mb-5">
    {% for page_number in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
      {% if page_number %}
        {% if page_number == posts.page %}
          <a class="btn btn-primary"
             href="{{ url_for('main.home', page=page_number) }}">{{ page_number }}</a>
        {% else %}
          <a class="btn btn-outline-primary"
             href="{{ url_for('main.home', page=page_number) }}">{{ page_number }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

flaskblog/templates/new_post.jinja2
{% extends "base.jinja2" %}
{% block content %}
  <div class="content-section col-12 col-md-6 col-lg-4">
    <form action="" method="post">
      {{ form.hidden_tag()}}
      <fieldset class="from-group">
        <legend>
          What do you think?
        </legend>
        <div class='mb-3'>
          {{ form.title.label(class='form-label')}}
          {% if form.title.errors %}
            {{ form.title(class='form-control')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.title.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.title(class='form-control')}}
          {% endif %}
        </div>
        <div class='mb-3'>
          {{ form.content.label(class='form-label')}}
          {% if form.content.errors %}
            {{ form.content(class='form-control submit-new-post')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.content.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.content(class='form-control submit-new-post')}}
          {% endif %}
        </div>
      </fieldset>
      <div class='mb-3'>{{ form.submit(class='btn btn-primary')}}</div>
    </form>
  </div>
{% endblock content %}

flaskblog/templates/post.jinja2
{% extends "base.jinja2" %}
{% block content %}
  <div class="post border rounded p-3 mb-3">
    <div class="post-card d-flex align-items-center flex-row  mb-3">
      <img src="{{ url_for('static', filename = 'profile_pics/' + post.author.profile_picture)}}"
           class="img-fluid rounded-circle me-4 "
           alt="profile pic">
      <div>
        <div class="card-text">
          <p class="mb-0">{{ post.author.username }}</p>
          <small class="text-muted">{{ post.date.strftime("%Y-%d-%m, %H:%M") }}</small>
        </div>
      </div>
      {% if current_user == post.author %}
        <div class="ms-4">
          <button class="btn btn-secondary btn-sm">
            <a href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          </button>
          <button type="button"
                  class="btn  btn-danger btn-sm"
                  data-bs-toggle="modal"
                  data-bs-target="#deleteModal">
            Delete
          </button>
          <!-- Modal -->
          <div class="modal fade"
               id="deleteModal"
               tabindex="-1"
               aria-labelledby="deleteModalLabel"
               aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this post ?</h5>
                  <button type="button"
                          class="btn-close"
                          data-bs-dismiss="modal"
                          aria-label="Close"></button>
                </div>
                <div class="modal-body">Deleted posts cannot be recovered</div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  <form action="{{ url_for('posts.delete_post', post_id=post.id) }}"
                        method="post">
                    <input type="submit" class="btn btn-danger" value="Delete post">
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
    <h5 class="card-title mb-2">{{ post.title }}</h5>
    <p>{{ post.content }}</p>
  </div>
{% endblock content %}

flaskblog/templates/register.jinja2
{% extends 'base.jinja2' %}
{% block content %}
  <div class="content-section col-12 col-md-6 col-lg-4">
    <form action="" method="post">
      {{ form.hidden_tag()}}
      <fieldset class="from-group">
        <legend>
          Join Today
        </legend>
        <div class="mb-3">
          {{ form.username.label(class='form-label')}}
          {% if form.username.errors %}
            {{ form.username(class='form-control')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.username.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.username(class='form-control')}}
          {% endif %}
        </div>
        <div class="mb-3">
          {{ form.email.label(class='form-label')}}
          {% if form.email.errors %}
            {{ form.email(class='form-control')}}
            <div class='invalid-feedback  d-block'>
              {% for error in form.email.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.email(class='form-control')}}
          {% endif %}
        </div>
        <div class="mb-3">
          {{ form.password.label(class='form-label', **{'aria-describedby':'passwordHelpBlock'})}}
          {% if form.password.errors %}
            {{ form.password(class='form-control')}}
            <div class='invalid-feedback  d-block'>
              {% for error in form.password.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.password(class='form-control', **{'aria-describedby':'passwordHelpBlock'})}}
            <div id="passwordHelpBlock" class="form-text">
              Your password must be at least 8 characters long, and must not contain spaces, special characters, or emoji.
            </div>
          {% endif %}
        </div>
        <div class="mb-3">
          {{ form.confirm_password.label(class='form-label')}}
          {% if form.confirm_password.errors %}
            {{ form.confirm_password(class='form-control')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.confirm_password.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.confirm_password(class='form-control')}}
          {% endif %}
        </div>
      </fieldset>
      <div>{{ form.submit(class='btn btn-primary mb-3')}}</div>
    </form>
    <div>
      <span>Do you already have an account? <a class="link-primary" href="{{ url_for('users.login')}}">Log in</a></span>
    </div>
  </div>
{% endblock content %}

flaskblog/templates/request_reset.jinja2
{% extends 'base.jinja2' %}
{% block content %}
  <div class="content-section col-12 col-md-6 col-lg-4">
    <form action="" method="post">
      {{ form.hidden_tag()}}
      <fieldset class="from-group">
        <legend>
          Reset Password
        </legend>
        <div class='mb-3'>
          {{ form.email.label(class='form-label')}}
          {% if form.email.errors %}
            {{ form.email(class='form-control')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.email.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.email(class='form-control')}}
          {% endif %}
        </div>
      </fieldset>
      <div class='mb-3'>{{ form.submit(class='btn btn-primary')}}</div>
    </form>
  </div>
{% endblock content %}

flaskblog/templates/reset_password.jinja2
{% extends 'base.jinja2' %}
{% block content %}
  <div class="content-section col-12 col-md-6 col-lg-4">
    <form action="" method="post">
      {{ form.hidden_tag()}}
      <fieldset class="from-group">
        <legend>
          Reset Password
        </legend>
        <div class='mb-3'>
          {{ form.password.label(class='form-label')}}
          {% if form.password.errors %}
            {{ form.password(class='form-control')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.password.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.password(class='form-control')}}
          {% endif %}
        </div>
        <div class='mb-3'>
          {{ form.confirm_password.label(class='form-label')}}
          {% if form.confirm_password.errors %}
            {{ form.confirm_password(class='form-control')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.confirm_password.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.confirm_password(class='form-control')}}
          {% endif %}
        </div>
      </fieldset>
      <div class='mb-3'>{{ form.submit(class='btn btn-primary')}}</div>
    </form>
  </div>
{% endblock content %}

flaskblog/templates/update_post.jinja2
{% extends "base.jinja2" %}
{% block content %}
  <div class="content-section col-12 col-md-6 col-lg-4">
    <form action="" method="post">
      {{ form.hidden_tag()}}
      <fieldset class="from-group">
        <legend>
          Update post
        </legend>
        <div class='mb-3'>
          {{ form.title.label(class='form-label')}}
          {% if form.title.errors %}
            {{ form.title(class='form-control user-post-update-input')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.title.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.title(class='form-control user-post-update-input')}}
          {% endif %}
        </div>
        <div class='mb-3'>
          {{ form.content.label(class='form-label')}}
          {% if form.content.errors %}
            {{ form.content(class='form-control submit-update-post user-post-update-input')}}
            <div class='invalid-feedback d-block'>
              {% for error in form.content.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.content(class='form-control submit-update-post user-post-update-input')}}
          {% endif %}
        </div>
      </fieldset>
      <div class='mb-3'>{{ form.submit(class='btn btn-primary  update-post-submit')}}</div>
    </form>
  </div>
{% endblock content %}

flaskblog/templates/user_posts.jinja2
{% extends "base.jinja2" %}
{% block content %}
  <h3 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h3>
  {% for post in posts.items %}
    <div class="post border rounded p-3 mb-3">
      <div class="post-card d-flex align-items-center flex-row  mb-3">
        <img src="{{ url_for('static', filename = 'profile_pics/' + post.author.profile_picture)}}"
             class="img-fluid rounded-circle me-4 "
             alt="profile pic">
        <div>
          <div class="card-text">
            <p class="mb-0">{{ post.author.username }}</p>
            <small ><a class="text-decoration-none text-muted"
   href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.date.strftime("%Y-%d-%m, %H:%M") }}</a></small>
          </div>
        </div>
      </div>
      <h5 class="card-title mb-2">
        <a class="link-dark" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
      </h5>
      <p>{{ post.content }}</p>
    </div>
  {% endfor %}
  <div class="mb-5">
    {% for page_number in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
      {% if page_number %}
        {% if page_number == posts.page %}
          <a class="btn btn-primary"
             href="{{ url_for('main.home', page=page_number) }}">{{ page_number }}</a>
        {% else %}
          <a class="btn btn-outline-primary"
             href="{{ url_for('main.home', page=page_number) }}">{{ page_number }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}